// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package com.example.grpc.order;

public interface MarketDataRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MarketDataRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 例如 "2330"
   * </pre>
   *
   * <code>string symbol = 1;</code>
   * @return The symbol.
   */
  java.lang.String getSymbol();
  /**
   * <pre>
   * 例如 "2330"
   * </pre>
   *
   * <code>string symbol = 1;</code>
   * @return The bytes for symbol.
   */
  com.google.protobuf.ByteString
      getSymbolBytes();
}
