// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package com.example.grpc.order;

public interface MarketDataResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MarketDataResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string symbol = 1;</code>
   * @return The symbol.
   */
  java.lang.String getSymbol();
  /**
   * <code>string symbol = 1;</code>
   * @return The bytes for symbol.
   */
  com.google.protobuf.ByteString
      getSymbolBytes();

  /**
   * <pre>
   * 當前價格
   * </pre>
   *
   * <code>double current_price = 2;</code>
   * @return The currentPrice.
   */
  double getCurrentPrice();
}
