// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package com.example.grpc.order;

public interface OrderRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OrderRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 注意：後面的 = 1 不是給值，而是這個欄位在二進位編碼中的「編號」
   * </pre>
   *
   * <code>string order_id = 1;</code>
   * @return The orderId.
   */
  java.lang.String getOrderId();
  /**
   * <pre>
   * 注意：後面的 = 1 不是給值，而是這個欄位在二進位編碼中的「編號」
   * </pre>
   *
   * <code>string order_id = 1;</code>
   * @return The bytes for orderId.
   */
  com.google.protobuf.ByteString
      getOrderIdBytes();
}
